---

 - name: Create installer directory
   file: 
       state=directory 
       path={{ mw_installer_folder }}
       owner={{ oracle_user }}
       group={{ oracle_group }}
       recurse=yes

 - name: Copy Middleware Installer
   copy: 
       src={{ mw_installer }} 
       dest={{ mw_installer_folder }} 
       owner={{ oracle_user }} 
       group={{ oracle_group }}

 - name: Copy file for silent installation
   template: 
          src=silent-weblogic.txt 
          dest={{ mw_installer_folder }}  
          owner={{ oracle_user }}
          group={{ oracle_group }}

 - name: Copy OraInst.loc
   template: 
          src=oraInst.loc  
          dest={{ mw_installer_folder }} 
          owner={{ oracle_user }} 
          group={{ oracle_group }}

 - name: execute Weblogic installer
   command: "{{ jdk_folder }}/bin/java -Xms512m -Xmx800m -jar {{ mw_installer_folder }}/{{ mw_installer }} -ignoreSysPrereqs -silent -responseFile {{ mw_installer_folder }}/silent-weblogic.txt -novalidation -invPtrLoc {{ mw_installer_folder }}/oraInst.loc"
   become: true
   become_user: weblogic
