---
 - name: install apache
   yum: name="{{item}}" state=latest
   with_items:
            - httpd
            - php
            - php-mysql
   tags:
     - packages
 - name: create vhost in apache
   file: path=/etc/httpd/conf.d/shekhar state=directory owner=root group=root mode=755
 - name: copy vhost file
   template:
          src: host.j2
          dest: /etc
#          remote: yes
          mode: 655
          owner: root
          group: root
          backup: no
          force: yes

# - name: start apache
#   service: name=httpd state=started
 - name: copying index.html
   template: 
      src=index.html.j2 dest=/var/www/html/index.html

   notify: restart apache
   tags:
     - restart
