 oracle_user: weblogic
 oracle_group: weblogic
 oracle_base: /u02/opt/
 oracle_password: '123456'
 
##JDK installer target and java path
 jdk_folder: '/u02/opt/java/jdk1.7.0_80'

###
 mw_installer: 'wls_121200.jar'

#database settings#
 dbserver_name: '172.31.25.236'
 dbserver_port: '1521'
 dbserver_service: 'XE'
 repository_prefix: 'shekhar'

#domain name
 domain_name: smsdev

# Nodemanager and server settings
 node_manager_listen_port: '5556'
 node_manager_listen_address: 'localhost'
 admin_server_hostname: 'localhost'
 admin_server_port: '7001'
 managed_server_name: 'sms_server1'
 managed_server_port: '7003'
