middleware_home: '{{ oracle_base }}/weblogic'
middleware_common_home: '{{ middleware_home }}/oracle_common'
domains_home: '{{ oracle_base }}/weblogic/domains'
applications_home: '{{ oracle_base }}/weblogic/applications'
mw_installer_folder: '{{ oracle_base }}/installer'
domain_home: '{{ domains_home }}/{{ domain_name }}'
#nodemanager_home: '{{ oracle_base }}/weblogic/domains/smsdev/nodemanagers/'
nodemanager_home: '{{ oracle_base }}/weblogic/oracle_common/common/nodemanager'
weblogic_home: '{{ middleware_home }}/wlserver'
nodemanager_username: 'weblogic'
weblogic_admin: 'weblogic'
admin_server_name: 'AdminServer'
server_hostname: '{{ ansible_fqdn }}'
managed_server_name: 'sms_server1'
